apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-frontend  
  namespace: default
spec:
  rules:
  - host: demo.192.168.192.19.xip.io
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
        pathType: ImplementationSpecific