apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveysolutions
spec:
  selector:
    matchLabels:
      app: surveysolutions
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: surveysolutions
        tier: frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: surveysolutions
        image: ghcr.io/surveysolutions/surveysolutions/headquarters:29541
        resources:
          requests:
            cpu: 600m
            memory: 800Mi        
        env:
        - name: HQ_ConnectionStrings__DefaultConnection
          value: 'Server=192.168.88.72;Port=5432;User Id=postgres;Password=Qwerty1234;Database=SurveySolutions'
        - name: HQ_Headquarters__BaseUrl
          value: https://demo-hq.alfeg.net
        ports:
        - containerPort: 80
