apiVersion: v1
kind: Service
metadata:
  name: surveysolutions
  labels:
    app: surveysolutions
    tier: frontend
spec:
  ports:
  - port: 80
  selector:
    app: surveysolutions
    tier: frontend
